import { useEffect, useState } from "react";
import { ComposableMap, Geographies, Geography, Line, Marker } from "react-simple-maps";
import type { NetworkFlow, ThreatAlert } from "@/types/dashboard";

type Location = { latitude: number; longitude: number; label: string };
const atlas = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json";
const cacheKey = "threatlens-ip-geolocation-v1";
function publicIp(ip: string) { return !/^(10\.|127\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(ip); }
function initialLocations(): Record<string, Location> { try { return JSON.parse(localStorage.getItem(cacheKey) ?? "{}") as Record<string, Location>; } catch { return {}; } }

export function WorldMap({ flows, alerts }: { flows: NetworkFlow[]; alerts: ThreatAlert[] }) {
  const [locations, setLocations] = useState<Record<string, Location>>(initialLocations); const [resolving, setResolving] = useState(false);
  const attacks = flows.filter(flow => flow.is_attack).slice(0, 12).map(flow => ({ source: flow.src_ip, target: flow.dst_ip, id: flow.id })).concat(alerts.slice(0, 12).map(alert => ({ source: alert.source_ip, target: alert.target_ip, id: alert.id })));
  useEffect(() => { const ips = [...new Set(attacks.flatMap(attack => [attack.source, attack.target]).filter(publicIp))].filter(ip => !locations[ip]); if (!ips.length) return; let active = true; setResolving(true); void (async () => { const next = { ...locations }; for (const ip of ips.slice(0, 20)) { try { const response = await fetch(`https://ipapi.co/${encodeURIComponent(ip)}/json/`); const data = await response.json() as { latitude?: number; longitude?: number; city?: string; country_name?: string }; if (typeof data.latitude === "number" && typeof data.longitude === "number") next[ip] = { latitude: data.latitude, longitude: data.longitude, label: data.city || data.country_name || ip }; } catch { /* Unresolvable addresses are intentionally not rendered. */ } } if (active) { setLocations(next); localStorage.setItem(cacheKey, JSON.stringify(next)); setResolving(false); } })(); return () => { active = false; }; }, [attacks, locations]);
  const mappable = attacks.filter(attack => locations[attack.source] && locations[attack.target]);
  return <section className="card col-span-full xl:col-span-7"><div className="card-head"><div><p className="eyebrow">Global telemetry</p><h2>Live threat origins</h2></div><span className="live-dot">{resolving ? "GEOLOCATING" : "LIVE"}</span></div><div className="relative overflow-hidden rounded-xl bg-slate-950"><ComposableMap projectionConfig={{ scale: 145 }} className="h-[270px] w-full" aria-label="World map of detected threat connections"><Geographies geography={atlas}>{({ geographies }) => geographies.map(geo => <Geography key={geo.rsmKey} geography={geo} fill="#17263a" stroke="#3b4a61" strokeWidth={0.35}/>)}</Geographies>{mappable.map(attack => <Line key={attack.id} className="threat-arc" from={[locations[attack.source].longitude, locations[attack.source].latitude]} to={[locations[attack.target].longitude, locations[attack.target].latitude]} stroke="#fb7185" strokeWidth={0.65} strokeLinecap="round"/>)}{[...new Set(mappable.flatMap(attack => [attack.source, attack.target]))].map(ip => <Marker key={ip} coordinates={[locations[ip].longitude, locations[ip].latitude]}><circle r={3} fill="#22d3ee" stroke="#07111e" strokeWidth={1.5}/><title>{`${ip} · ${locations[ip].label}`}</title></Marker>)}</ComposableMap><div className="absolute bottom-3 left-4 font-mono text-[10px] text-slate-400">{mappable.length ? `${mappable.length} geolocated attack paths` : "Waiting for public-IP geolocation data"}</div></div><p className="mt-3 text-xs text-slate-500">World Atlas country geometry. Public IP coordinates are resolved via ipapi.co and cached locally; private addresses are not mapped.</p></section>;
}
