"""initial schema

Revision ID: a8bc5c95cf75
Revises: 
Create Date: 2026-08-26 10:35:19.531005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.models


# revision identifiers, used by Alembic.
revision: str = 'a8bc5c95cf75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('cpu_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('memory_mb', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('predictions_count', sa.BigInteger(), nullable=False),
    sa.Column('threats_detected', sa.BigInteger(), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('f1_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_name')
    )
    op.create_table('dga_domains',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('entropy', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('vowel_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('is_dga', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('dns_queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(length=64), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=False),
    sa.Column('server_ip', sa.String(length=45), nullable=False),
    sa.Column('query_name', sa.String(length=255), nullable=False),
    sa.Column('query_type', sa.String(length=10), nullable=False),
    sa.Column('response_code', sa.String(length=16), nullable=False),
    sa.Column('payload_size_bytes', sa.Integer(), nullable=False),
    sa.Column('entropy', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_tunneling', sa.Boolean(), nullable=False),
    sa.Column('tunneling_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id')
    )
    op.create_table('network_flows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flow_id', sa.String(length=64), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('bytes_in', sa.BigInteger(), nullable=False),
    sa.Column('bytes_out', sa.BigInteger(), nullable=False),
    sa.Column('pkts_in', sa.Integer(), nullable=False),
    sa.Column('pkts_out', sa.Integer(), nullable=False),
    sa.Column('tcp_flags', sa.String(length=32), nullable=True),
    sa.Column('flow_rate_bps', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('packet_rate_pps', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('entropy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ja3_hash', sa.String(length=64), nullable=True),
    sa.Column('is_attack', sa.Boolean(), nullable=False),
    sa.Column('attack_type', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id')
    )
    op.create_table('threat_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('attack_type', sa.String(length=64), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('target_ip', sa.String(length=45), nullable=False),
    sa.Column('target_port', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('contributing_bots', app.db.models.ArrayType(), nullable=False),
    sa.Column('bot_scores', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('blockchain_verified', sa.Boolean(), nullable=False),
    sa.Column('blockchain_block_num', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_table('blockchain_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('alert_hash', sa.String(length=66), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('sender_address', sa.String(length=42), nullable=False),
    sa.Column('gas_used', sa.BigInteger(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['threat_alerts.alert_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_hash'),
    sa.UniqueConstraint('tx_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blockchain_logs')
    op.drop_table('threat_alerts')
    op.drop_table('network_flows')
    op.drop_table('dns_queries')
    op.drop_table('dga_domains')
    op.drop_table('bot_metrics')
    # ### end Alembic commands ###
