import { useEffect, useState } from "react";
import { AlertsFeed } from "@/components/AlertsFeed";
import { BotHealthGrid } from "@/components/BotHealthGrid";
import { LiveTrafficPanel } from "@/components/LiveTrafficPanel";
import { ThemeToggle } from "@/components/ThemeToggle";
import type { BotMetric, NetworkFlow, ThreatAlert } from "@/types/dashboard";
const base = import.meta.env.VITE_API_BASE_URL ?? "";
function useData<T>(path: string) { const [data, setData] = useState<T[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { let mounted = true; const load = async () => { try { const response = await fetch(`${base}${path}`); if (!response.ok) throw new Error(`HTTP ${response.status}`); const body = await response.json() as T[]; if (mounted) { setData(body); setError(""); } } catch (err) { if (mounted) setError(err instanceof Error ? err.message : "Request failed"); } finally { if (mounted) setLoading(false); } }; void load(); const id = window.setInterval(() => void load(), 3000); return () => { mounted = false; window.clearInterval(id); }; }, [path]); return { data, loading, error }; }
function Page({ title, children, loading, error }: { title: string; children: React.ReactNode; loading: boolean; error: string }) { return <main className="min-w-0 flex-1 p-4 sm:p-7"><p className="eyebrow">ThreatLens operations</p><h1 className="mb-5 text-2xl font-semibold text-slate-900 dark:text-white">{title}</h1>{error && <p className="mb-4 rounded-lg border border-red-400/40 bg-red-400/10 p-3 text-sm text-red-700 dark:text-red-300">Could not load live data: {error}</p>}{loading ? <p className="card text-sm text-slate-500">Loading live data…</p> : children}</main>; }
export function TrafficPage() { const result = useData<NetworkFlow>("/api/flows?limit=20"); return <Page title="Live traffic" {...result}><div className="grid grid-cols-12 gap-4"><LiveTrafficPanel flows={result.data} connected={false}/></div></Page>; }
export function AlertsPage() { const result = useData<ThreatAlert>("/api/alerts?limit=50"); return <Page title="Alerts" {...result}><div className="grid grid-cols-12 gap-4"><AlertsFeed alerts={result.data}/></div></Page>; }
export function BotsPage() { const result = useData<BotMetric>("/api/bots/health"); return <Page title="Specialist bot health" {...result}><div className="grid grid-cols-12 gap-4"><BotHealthGrid bots={result.data}/></div></Page>; }
export function BlockchainPage() { const result = useData<ThreatAlert>("/api/alerts?limit=50"); const verified = result.data.filter(alert => alert.blockchain_verified || alert.blockchain_tx_hash); return <Page title="Blockchain verification" {...result}>{verified.length ? <div className="card"><p className="mb-3 text-sm text-slate-500">Alerts with blockchain audit records</p>{verified.map(alert => <div className="border-t border-slate-200 py-3 text-sm dark:border-slate-800" key={alert.id}><b>{alert.title}</b><span className="ml-3 font-mono text-xs text-slate-500">{alert.blockchain_tx_hash ?? "Verification pending"}</span></div>)}</div> : <div className="card text-sm text-slate-500">No alert has a blockchain verification record yet.</div>}</Page>; }
export function SettingsPage({ dark, toggle }: { dark: boolean; toggle: () => void }) { return <main className="min-w-0 flex-1 p-4 sm:p-7"><p className="eyebrow">ThreatLens operations</p><h1 className="mb-5 text-2xl font-semibold text-slate-900 dark:text-white">Settings</h1><div className="card flex items-center justify-between"><div><h2>Appearance</h2><p className="mt-1 text-sm text-slate-500">Saved in this browser and applied across the dashboard.</p></div><ThemeToggle dark={dark} onToggle={toggle}/></div></main>; }
